### ISSUE TITLE
Improve logging of loaded functions when hosted

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#10928]
#### What problem would the feature you're requesting solve? Please describe.
When debugging locally with the Core Tools, you get a clear log of what Functions are loaded, as well as the endpoint for any HTTP triggers:

```
Functions:

        Function1: [GET,POST] http://localhost:7001/api/Function1

        BlobFunction: blobTrigger

        Function: timerTrigger

```

This is handy as a spot check. However, there isn't really an equivalent when deployed as service. Some information is logged about listeners, and for HTTP triggers there's a bit more, but these tend to be scattered, and there isn't a clear way to just get the list of Functions that were loaded.

#### Describe the solution you'd like
A log or sequence of logs should inform the user of each function that was loaded, as well as its trigger type.

#### Describe alternatives you've considered
Other methods can be used as well (such as the endpoints to list functions), but this is diagnostic information which should be available when troubleshooting issues with a given function loading, etc.
