### ISSUE TITLE
Add configuration for enabling only HTTP or only non-HTTP functions

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#4412]
#### What problem would the feature you're requesting solve? Please describe.
When deploying function apps containing HTTP and non-HTTP functions to Kubernetes running KEDA/Osiris, we need to split the app into 2 deployments. The Functions Core Tools figures out which functions need to be enabled/disabled in the HTTP and non-HTTP deployments and generates the correct environment variables. For instance:

```yaml
env:
  - name: AzureFunctionsJobHost__functions__0
    value: QueueTrigger
  - name: AzureFunctionsJobHost__functions__1
    value: QueueTrigger1
```

This is difficult to do when manually creating deployment scripts for deploying function apps to the environment and also makes it difficult for the Core Tools to use helm for deployment.

#### Describe the solution you'd like
- Add a way to enable only HTTP functions in a function app
- Add a way to enable only non-HTTP functions in a function app

#### Describe alternatives you've considered
Manually creating the correct the environment variables in the deployment scripts, and making sure they stay in sync with the function app.
