### ISSUE TITLE
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by thomasvdb** [Azure/azure-functions-host#5832]
#### Investigative information
- Timestamp: 2020-03-26 09:48:09.304
- Function App version: 3.0.13139.0
- Invocation ID: 5da3c701a5a9704fac16e60bc400e607
- Region: West-Europe

After deploying our Azure Function (which was recently upgrade from .NET Core 2.2 to .NET Core 3.1), we sometimes receive the following error:
```
An exception occurred in the database while iterating the results of a query for context type 
'...SourceContext'.
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform
```

If we then switch the Runtime version of the Azure Function to v2 and back to v3; the issue is solved.
What strikes me when watching the logs is the following entry when the error occurs:
```
Entity Framework Core 2.1.1-rtm-30846 initialized '...SourceContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
```

I've checked and the DLLs in the ZIP are all 3.1 DLLs for Entity Framework Core.
We also do a clean during the build to prevent any leftover DLLs.

#### Repro steps
This is our YAML file for the App Service Deploy of the Function (values are changed to dummy values).

```
variables:
  functionsAppName: 'ourapplicationname'

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: $(functionsAppName)'
  inputs:
    azureSubscription: 'subscriptionname'
    appType: functionApp
    WebAppName: '$(functionsAppName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/ProjectName/drop/ProjectName.zip'
```

#### Actual behavior
Exception thrown by querying our database in the Azure Function.
```
An exception occurred in the database while iterating the results of a query for context type 
'...SourceContext'.
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform
```

#### Known workarounds
Switch to Azure Function v2 in the portal and back to v3 right away.

#### Related information 
- .NET Core 3.1
- Azure Function is written in .NET and uses a Service Bus trigger
- Entity Framework Core 3.1.1
- Microsoft.NET.Sdk.Functions 3.0.5
