### ISSUE TITLE
Azure Function returns 404 after adding bindings to blob storage 

### ISSUE THREAD

**Issue by Tobmeister** [Azure/azure-functions-host#6705]
#### Summary

I created a new Azure Function (Python, on Linux, Consumption Plan, HTTP Trigger). The purpose of the function is to read and write data using a blob storage via GET and POST request, respectively.

#### Investigative information

- Function App version: V2
- Function App name: (prefer not to publish, see data below)
- Invocation ID: not available, function is broken completely. Providing invocation UUID and timestamp below
- Invocation with UUID: https://<myfunctionname>.azurewebsites.net/api/e620ba98-aca6-222f-adec-d9055eb9651c
- Invocation timestamp (UTC): Date: Sun, 27 Sep 2020 09:37:28
- Region: West Europe

#### Repro steps

1. Create a new Azure Function (Python on Linux) with HTTP trigger through the portal. App will contain the standard starter code.
2. Verify the function reacts to a GET request as per the standard starter code.
3. Create or use a general purpose storage account in the same resource group.
4. Create a new blob container in that storage account.
5. Upload a blob (JSON file) into the root folder of that blob container.
6. Add the POST method to the HTTP Trigger bindings in `function.json`.
7. Add blob storage bindings for `in` and `out` directions to `function.json`.
8. Make sure the Function App setting "AzureWebJobsStorage" contains the correct connection string of the storage account.
9. Redeploy the function. I am using an Azure DevOps CI/CD pipeline.
10. Call the function using either GET or POST request.

Find the code of `function.json` below.

#### Expected behavior

GET or POST requests return HTTP 200 and the function returns the same responses as before.

#### Actual behavior

- GET or POST requests return HTTP 404.
- No function execution is displayed in the Azure Portal (Function App Overview).
- No function execution is displayed in Application Insights.
- No function execution is displayed in the Log Stream.

#### Known workarounds

None.

#### Related information 

This is the content of my `function.json`:

```yaml
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "program",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    },
    {
      "type": "blob",
      "direction": "in",
      "name": "inputblob",
      "path": "<my-blob-container-name>/<my-blob-name>",
      "connection": "AzureWebJobsStorage"
    },
    {
      "type": "blob",
      "direction": "out",
      "name": "outputblob",
      "path": "<my-blob-container-name>/<my-blob-name>",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
````

At this time, the function `main` method signature is still unchanged:
```javascript
def main(req: func.HttpRequest) -> func.HttpResponse:
```

Extending it with the parameters defined in the binding, which would be the next step to do, does not change the behavior though.
```javascript
def main(req: func.HttpRequest, inputblob: func.InputStream, outputblob: func.Out[func.InputStream]) -> func.HttpResponse:
```
