### ISSUE TITLE
Functions Host restarting when hitting Kubernetes resource limits

### ISSUE THREAD

**Issue by jimmyjamesbaldwin** [Azure/azure-functions-host#7009]
#### Issue Summary
Hi, I'm experiencing some trouble running an Azure Function app on our AKS cluster. My issue is that when enforcing memory resource limits on the deployment, when under heavy load the memory consumption increases and as it approaches the limit the Functions Host service inside the container dies and restarts (note the container still stays alive just the Host inside restarts). Is this a known issues/is there a potential solution?

#### Investigative information

Please provide the following:

- Timestamp: 2020-12-23T19:26:56+00:00
- Function App version: na
- Function App name: notebookrunner
- Function app container image: mcr.microsoft.com/azure-functions/python:2.0-python3.7-appservice
- Function name(s) (as appropriate): execute-notebook
- Invocation ID: na
- Region: na

#### Repro steps

1. Create a Dockerfile using the function image similar to:
```
FROM mcr.microsoft.com/azure-functions/python:2.0-python3.7-appservice

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
        PIP_CONFIG_FILE=/pipconfig/pip.ini

# boring build steps

COPY . /home/site/wwwroot
```
2. Create a Deployment spec similar to :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebookrunner
  namespace: notebookrunner
spec:
  template:
    spec:
      containers:
      - env:
        - name: FUNCTIONS_WORKER_PROCESS_COUNT
          value: "1"
        - name: AzureFunctionsJobHost__logging__LogLevel__Default
          value: Trace
        image: <myimage>
        name: notebookrunner
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
```
3. Execute a memory intensive function within the Function app (eg process a jupyter notebook that uses a large dataset)

#### Expected behavior

My expectation was that the Function host would still stay up but be bound by the memory limit rather than crashing. My assumption was that it would start paging to disk once it hits the memory limit but this appears to not be the case - could someone clarify the actual behaviour for me?

#### Actual behavior

After deploying the app described in Repro Steps, when the app is under load and memory consumption increases the following behaviour occurs:

1. As the application becomes under load it's possible to see the memory usage creep up towards the limit using `kubectl top pod`, before dropping back down again after the Function Host crashes and restarts:
```
Wed Dec 23 16:30:11 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 250m 692Mi
Wed Dec 23 16:30:12 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 250m 692Mi
Wed Dec 23 16:30:13 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 250m 692Mi
Wed Dec 23 16:30:43 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 250m 692Mi
Wed Dec 23 16:30:54 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 251m 763Mi
Wed Dec 23 16:30:55 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 251m 763Mi
Wed Dec 23 16:30:56 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 251m 763Mi
Wed Dec 23 16:31:40 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 251m 763Mi
Wed Dec 23 16:31:52 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 243m 819Mi
Wed Dec 23 16:31:53 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 243m 819Mi
Wed Dec 23 16:32:17 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 243m 819Mi
Wed Dec 23 16:32:51 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 243m 819Mi
Wed Dec 23 16:32:52 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 4m 163Mi
Wed Dec 23 16:32:54 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 4m 163Mi
Wed Dec 23 16:32:55 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 4m 163Mi
Wed Dec 23 16:32:56 UTC 2020 notebookrunner-7cdc6b8c5f-n2q5c 4m 163Mi
```
2. Viewing the docker logs for this container reveals that the Function Host was killed by something, although Kubernetes believes the container is still running without issue:
```
info: Function.execute-notebook.User[0]
      Index has no name, defaulting to 'index'
info: Function.execute-notebook.User[0]
      Index has no name, defaulting to 'index'
/azure-functions-host/start.sh: line 28:    21 Killed                  /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost
```

#### Known workarounds

NA

Any help greatly appreciated! Happy to post most logs if required - many thanks
