### ISSUE TITLE
[Linux Consumption] Successful slot swaps automatically reverted after a few minutes

### ISSUE THREAD

**Issue by andrewconnell** [Azure/azure-functions-host#7336]
> I know I've listed `n/a` a few times in this issue, but that's because this has nothing to do with the code or a specific invocation of the function. This happens with the default Node.js function app project created in VS Code... looks more like a runtime/host issue than a code issue.

#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version: ~3
- Function App name: totalview-playground4-linux-consumption
- Function name(s) (as appropriate): all
- Invocation ID: n/a
- Region: East US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create new Azure Function Linux Consumption app service
2. Create a 2nd deployment slot **staging**
3. Deploy app to **staging** slot

    > test function... this works

4. Swap slots & wait for the process to complete
5. Observe the functions are now listed under the production slot:
  
    ![image](https://user-images.githubusercontent.com/2068657/117044479-7c1d2700-acdc-11eb-8817-37d0c75911e6.png)

6. Wait a few minutes (~5-10... usually I see this around 9m after the successful slot deployment)
7. Retry the function on the production slot = failure
8. Observe the functions are no longer listed on the production slot:

    ![image](https://user-images.githubusercontent.com/2068657/117044622-a66ee480-acdc-11eb-8122-a40db1313ee1.png)

9. go back and list functions on the staging slot... observe a phantom swap has occurred

#### Expected behavior

Expect that after a successful slot swap, the swap isn't reverted.

#### Actual behavior

See repro steps.

#### Known workarounds

Don't use Linux Consumption plan... if I create an Windows Consumption plan, it works as expected.

#### Related information 

* Programming language used: Node.js
* Links to source: n/a
* Bindings used: HTTP trigger

For the Q/A on this issue that led me here to post a bug, please see the following. I've included all details in this issue, but including this to show others have had the same experience.
https://docs.microsoft.com/en-us/answers/questions/382139/az-function-consumption-plan-reverts-production-sl.html

**Comment by balag0** [comment]
@andrewconnell I tried this but couldn't repro it myself. Could you provide more details on how you are deploying to the staging slot in step 3?

**Comment by andrewconnell** [comment]
@balag0 I'm deploying to staging via a GitHub action:

```yml
      ######################################################################
      # login to Azure CLI via service principal
      ######################################################################
      - name: Login to Azure
        run: az login --service-principal --tenant $BOT_TENANT_ID --username $BOT_CLIENT_ID --password $BOT_CLIENT_SECRET
        env:
          BOT_TENANT_ID: ${{ secrets.TOTALVIEW_BOT_AZURE_TENANTID }}
          BOT_CLIENT_ID: ${{ secrets.TOTALVIEW_BOT_AZURE_CLIENTID }}
          BOT_CLIENT_SECRET: ${{ secrets.TOTALVIEW_BOT_AZURE_CLIENTSECRET }}

      ######################################################################
      # acquire publish profile for Azure Functions App
      ######################################################################
      - name: Download Azure Function app publishing profile
        id: az_funcapp_publishing_profile
        run: |
          CMD_PUB_PROFILE=$(az functionapp deployment list-publishing-profiles --subscription $AZURE_SUBSCRIPTION_ID --resource-group $FUNCTION_APP_RESOURCE_GROUP --name $FUNCTION_APP_NAME --slot $FUNCTION_APP_DEPLOYMENT_SLOT --xml)
          echo "::set-output name=slot_pub_profile::${CMD_PUB_PROFILE}"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_FUNCTIONAPP_SUBSCRIPTIONID }}
          FUNCTION_APP_RESOURCE_GROUP: ${{ secrets.AZURE_FUNCTIONAPP_RESOURCEGROUP }}
          FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          FUNCTION_APP_DEPLOYMENT_SLOT: ${{ env.AZURE_FUNCTION_APP_DEPLOYMENT_SLOT }}

      ######################################################################
      # deploy function app
      ######################################################################
      - name: Deploy Azure Functions app
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          publish-profile: ${{ steps.az_funcapp_publishing_profile.outputs.slot_pub_profile }}
          respect-funcignore: true

      ######################################################################
      # update azure function app setting to commit hash
      ######################################################################
      - name: Set Azure Function app's app setting "APP_VERSION" & "COMMIT_HASH"
        run: |
          az functionapp config appsettings set --resource-group $FUNCTION_APP_RESOURCE_GROUP --name $FUNCTION_APP_NAME --slot $FUNCTION_APP_DEPLOYMENT_SLOT --slot-settings "APP_VERSION=$SLOT_SETTING__APP_VERSION" "COMMIT_HASH=$SLOT_SETTING__COMMIT_HASH"
        env:
          FUNCTION_APP_RESOURCE_GROUP: ${{ secrets.AZURE_FUNCTIONAPP_RESOURCEGROUP }}
          FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          FUNCTION_APP_DEPLOYMENT_SLOT: ${{ env.AZURE_FUNCTION_APP_DEPLOYMENT_SLOT }}
          SLOT_SETTING__APP_VERSION: staging
          SLOT_SETTING__COMMIT_HASH: ${{ github.sha }}
```

Then, when I want to swap the slots, in another workflow I do the following:

```yml
      ######################################################################
      # login to Azure CLI via service principal
      ######################################################################
      - name: Login to Azure
        run: az login --service-principal --tenant $BOT_TENANT_ID --username $BOT_CLIENT_ID --password $BOT_CLIENT_SECRET
        env:
          BOT_TENANT_ID: ${{ secrets.TOTALVIEW_BOT_AZURE_TENANTID }}
          BOT_CLIENT_ID: ${{ secrets.TOTALVIEW_BOT_AZURE_CLIENTID }}
          BOT_CLIENT_SECRET: ${{ secrets.TOTALVIEW_BOT_AZURE_CLIENTSECRET }}

      ######################################################################
      # swap deployment slots
      ######################################################################
      - name: Swap staging & production deployment slot
        run: |
          az functionapp deployment slot swap --resource-group $FUNCTION_APP_RESOURCE_GROUP --name $FUNCTION_APP_NAME --slot $FUNCTION_APP_STAGING_SLOT --target-slot $FUNCTION_APP_PRODUCTION_SLOT
        env:
          FUNCTION_APP_RESOURCE_GROUP: ${{ secrets.AZURE_FUNCTIONAPP_RESOURCEGROUP }}
          FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          FUNCTION_APP_STAGING_SLOT: ${{ env.AZURE_FUNCTION_APP_STAGING_DEPLOYMENT_SLOT }}
          FUNCTION_APP_PRODUCTION_SLOT: production
```

BTW, these exact same workflows work when I target a Windows based Consumption AzFunction app. I used the same repo in  my test and only changed the name of the function app I'm targeting via the secret `${{ secrets.AZURE_FUNCTIONAPP_NAME }}`
