### ISSUE TITLE
Permissions failure executing chromium with Playwright.dev in Linux Consumption with Github Actions

### ISSUE THREAD

**Issue by MrSimonC** [Azure/azure-functions-host#7893]
Hello all!

I'm getting permission error thrown when trying to implement implement PlayWright.net in a Linux Azure Function via github actions.

The goal would be that anyone can use PlayWright .net in an Azure Function (Linux) Consumption plan and by using github actions, this makes it platform / tool agnostic (e.g. VS in windows, or VC code on mac/linux).

## Learnings

I've been trying to get this to work for days now, so a few things I've learned:

* This will have to be a Linux based consumption plan (since windows doesn't have the required dlls)
* [Anthony Chu has gotten PlayWright .js working](https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/) with a javascript function deploying from VS Code Azure Functions extension
* [horihiro](https://github.com/horihiro/azure-functions-playwright-dotnet5-linux-consumption) is the only person on the internet I've found (at time of writing) who has gotten PlayWright .net working with a C# function by deploying from VS Code Azure Functions extension inside of a wsl2 linux dev container (to .net 5 isolated process)
* Both approaches use VS Code Azure Function extension which does Kudu remote build by default, which detects `npm install` in Anthoy's case and `node cli.js install chrome` in horihiro's case.
* I've replicated horihiro's success in a windows VM, with WSL2 and a linux container, so have used this output as a basis to match my github-actions deployment script (mirroring his file structure). Ideally I'd target .net 6 in-process, but for now, I'm replicating .net 5 isolated to match horihiro's output (also playwright only targets .net 5 at the moment)
* My github action script is not doing a remote build on Kudu *(which I hope to avoid since github actions are way easier to write than a Kudu deployment script)*

## Repo address

https://github.com/MrSimonC/Linux5AzFnIsolated

### Github actions script

https://github.com/MrSimonC/Linux5AzFnIsolated/blob/master/.github/workflows/Linux5AzFnIsolated.yml

## Error when running the function

Error I get when I run the function in Azure (Linux Consumption plan):
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.Function1
 ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Permission denied)
 ---> System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Playwright.Transport.StdIOTransport..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
   at Linux5AzFnIsolated.Function1.Run(HttpRequestData req, FunctionContext executionContext) in /home/runner/work/Linux5AzFnIsolated/Linux5AzFnIsolated/Linux5AzFnIsolated/Function1.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
```

All my reading indicates that the chrome binary executable (or the .playwright) folder's executable bit has been lost. <br>
Since I can prove that on the ubuntu build server (container) all executable permissions seem to be kept (see github actions file for evidence) that it must be the final github actions deployment stage which is removing permissions (or something else happening).

I saw that [PR5834](https://github.com/Azure/azure-functions-host/pull/5834), went through to address custom handlers executable permissions - but if the github action deployment step is stripping the executable bit, then, analysing the PR5834 actual code/call hierachy, it looks like only the dotnet muxer path, or `nugetFilePath` would be updated to add in executable permissions.

Does anyone have any other suggestions or, can look into whether my theory is correct / not?

*(This is pretty much my first ever big issue I've raised on github and my first ever to Microsoft, so be kind 😏 )*

#### Investigative information

Please provide the following:

- Timestamp: 25/11/2021 12:21
- Function App version: host ~3 targeting .net 5 isolated
- Function App name: Linux5AzFnIsolated
- Function name(s) (as appropriate): Function1
- Invocation ID: n/a
- Region: UK West

#### Repro steps
See repo code above, but essentially any Http triggered app with the code:

`using var playwright = await Playwright.CreateAsync();`

...which will output the error shown above.

#### local.settings.json file

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsDashboard": "....",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_EXTENSION_VERSION": "~3",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "APPINSIGHTS_INSTRUMENTATIONKEY": "....",
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "....",
    "WEBSITE_MOUNT_ENABLED": "1",
    "PLAYWRIGHT_BROWSERS_PATH": "/home/site/wwwroot/.playwright",
    "DEBUG": "pw:api"
  }
}
```

**Comment by anthonychu** [comment]
Started some discussions with @marcusfelling on how to improve the Playwright experience on Functions. As you’ve noticed, this doesn’t work well right now, especially for .NET.

**Comment by horihiro** [comment]
@MrSimonC , 
As far as I know, you can choose deployment way from the following to keep executable permission on Linux Consumption.
1. ZipDeploy with Remote Build
2. Run From Package (uploading a zip package to a storage account and setting `WEBSITE_RUN_FROM_PACKAGE` to the package url)

I tried 1. but Remote Build is not succeeded yet for .NET5 functions in my environment.

So 2. is recommended way. To deploy by Run From Package in GitHub Action, you can use [`Using Azure Service Principal for RBAC as Deployment Credential`](
https://github.com/marketplace/actions/azure-functions-action#using-azure-service-principal-for-rbac-as-deployment-credential).

I confirmed that the following action can keep the permission. I updated your action with the following:
  - comment out `publish-profile` in `azure/functions-action@1` and add `azure/login@v1` action for RBAC deploy instead
  - add `azure/appservice-settings@v1` for setting some App Settings.

https://github.com/horihiro/Linux5AzFnIsolated/blob/1d67b457733e15c3f75408bf36b6d78f0613bccf/.github/workflows/Linux5AzFnIsolated-azlogin.yml#L53-L67
```yml
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        # publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        mask-inputs: false
        app-settings-json: '[{ "name": "WEBSITE_MOUNT_ENABLED", "value": 1, "slotSetting": false }, { "name": "FUNCTIONS_WORKER_RUNTIME", "value": "dotnet-isolated", "slotSetting": false }, { "name": "PLAYWRIGHT_BROWSERS_PATH", "value": "/home/site/wwwroot/.playwright/ms-playwright", "slotSetting": false }]'
```

**Comment by MrSimonC** [comment]
Big thanks from me @horihiro. I've replicated your success thanks to your notes. I've found that I can get this working on both .net 5 isolated and .net 6 isolated processes. It seems that Playwright doesn't even want to install on .net 6 in-process, but since the future will be out-of-process, if I (or anyone) needs to use durable functions, they can just create another, simple in-proc Function App and call it.

I've tried to come up with a fool-proof, simple way for others to get this working (on Windows, using Visual Studio):

1. Visual Studio, add new Isolated Function
2. Push to new github repo
3. Publish to Azure (Linux consumption), choose github actions CI/CD
4. Add playwright code & nuget reference
5. Add AZURE_CREDENTIALS to github secrets:
- Install Azure CLI
- In windows git bash, add MSYS_NO_PATHCONV=1 in computer environment variables
[see issue](https://github.com/Azure/azure-cli/issues/16317)
- Generate a service principle (contributor) in your subscription & add to github secrets:
<https://github.com/marketplace/actions/azure-app-service-settings#configure-github-secrets-with-azure-credentials-app-settings-and-connection-strings>
6. Update the auto-generated github actions .yml file with:

```yaml
env:
    # If targeting .net 6, Playwright needs .net 5:
    DOTNET_CORE_VERSION_PLAYWRIGHT: 5.0.x
    # download playwright browser to our app's folder, not ~/.cache/ms-playwright
    PLAYWRIGHT_BROWSERS_PATH: NameOfMyApp/publish/.playwright/ms-playwright

jobs:
    # If targeting .net 6, Playwright needs .net 5:
    - name: Setup .NET Core for Playwright
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION_PLAYWRIGHT }}
    
    # add after publish step:
    - name: Playwright install
      shell: bash
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install chromium
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # In the "Deploy to Azure Function App" step:
    # remove "publish-profile"
    
    # add after deploy step:
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        mask-inputs: false
        app-settings-json: '[{ "name": "WEBSITE_MOUNT_ENABLED", "value": 1, "slotSetting": false }, { "name": "FUNCTIONS_WORKER_RUNTIME", "value": "dotnet-isolated", "slotSetting": false }, { "name": "PLAYWRIGHT_BROWSERS_PATH", "value": "/home/site/wwwroot/.playwright/ms-playwright", "slotSetting": false }]'
```
