### ISSUE TITLE
Azure Function running on Kubernetes with Function level authorisation always unauthorised

### ISSUE THREAD

**Issue by matthewpavia99** [Azure/azure-functions-host#9049]
Azure function is running on a local kubernetes cluster. The HTTP triggered endpoints have Function-level authorisation. To set the required secrets we have exactly followed the steps as described in the pull request [#4462](https://github.com/Azure/azure-functions-host/pull/4462). We have also set up RBAC so that the secrets may be accesed by the function. Still when calling the http endpoint (example localhost:5000/api/Ping?code=masterkey) we are still getting 401 Unauthorized. Is there something we are missing or doing wrongly?

This role is applied to a service principal used by the pod:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
   name: secret-reader
rules:
- apiGroups: [""] 
  resources: ["secrets"]  
  verbs: ["create","list","patch","update","get","list"]
```
The Kubernetes secret:

```
apiVersion: v1
kind: Secret
metadata:  
	name: testfunction-function-keys
type: Opaque
data:  
	host.master: {{ .Values.TestFunction.hostkey | b64enc | quote}}  
	function.HttpTrigger.default: {{ .Values.TestFunction.triggerkey | b64enc | quote}}
```

Added to deployment:

```
volumes:      
- name: testfunction-function-keys        
secret:          
	secretName: testfunction-function-keys            
defaultMode: 0666   
```

Added to deployment container:

```
volumeMounts:          
	name: testfunction-function-keys           
	mountPath: "/run/secrets/functions-keys"            
	readOnly: true
```

#### Investigative information

Please provide the following:

- Function App version: 2.0
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: Local Kubernetes

#### Expected behavior

HTTP endpoint should be reachable when providing the function key.

#### Actual behavior

401 Unauthorized error

#### Known workarounds

None
